### ISSUE TITLE
Can I use it without rails?

### ISSUE THREAD

**Issue by ccmywish** [AndyObtiva/glimmer-dsl-opal#26]
Hi @AndyObtiva 

I think the whole idea is very cool, especially `the BOOM`.

However, the readme says we should install rails as a prerequisite, Can I use it without rails? 

Is it possible to use it as the front-end tech only?

**Comment by AndyObtiva** [comment]
No, this project is available for use in Rails only. But, it is getting replaced by [Glimmer DSL for Web](https://github.com/AndyObtiva/glimmer-dsl-web), which should offer a more web-like approach to the Glimmer GUI DSL that better leverages existing HTML/CSS/JS skills. [Glimmer DSL for Web](https://github.com/AndyObtiva/glimmer-dsl-web) also runs in Rails only.
