### ISSUE TITLE
Tetris example via sinatra?

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer-dsl-opal#4]
Hello Andy,

You already added an example with rails for the tetris example.

I am wondering how to add tetris to sinatra (I actually use sinatra more than rails).

I could then e. g. add a route /tetris and offer the tetris variant via sinatra. :D

So the TL;DR request: could you, if time permits, also add a minimal example
on the README that shows how to use this via sinatra? (Here we can assume
the user already installed all of glimmer including glimmer-dsl-opal and probably
opal as well, so only a standalone example may be needed; perhaps even
a standalone .rb file or something, or just a route-added example - either way
is fine).

**Comment by AndyObtiva** [comment]
I am sorry, but [Rails](https://github.com/rails/rails) is the only web platform I recommend for Glimmer DSL for Opal. Given that the project is open-source, you are welcome to explore other options on your own.
